[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "reflex>=0.6.8",
    "reflex>=0.6.0a",
    "reflex-chakra"
]
